# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'coruja' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for coruja

  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  target 'corujaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'coruja-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for coruja-tvOS

  target 'coruja-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
